services:
  app:
    build: .
    restart: always
    container_name: healtcare-api
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_DATABASE}
